management:
  security:
    enabled: false 
security:
  basic:
    enabled: false
logging:
  level:
    io:
      pivotal:
        training: INFO 
spring:
  cloud:
    services:
      registrationMethod: direct